version: "2.4"

services:
  build_foobar:
    image: foobar:1.0.0
    build:
      context: ./

  build_barbaz:
    image: foobar.com/barbaz:1.0.0
    build:
     context: ./subdir
     dockerfile: barbaz.Dockerfile
