version: "2.4"

services:
  build_foobar:
    image: foobar:${VERSION}
    build:
      context: ./

  build_barbaz:
    image: foobar.com/barbaz:${VERSION}
    build:
     context: ./subdir
     dockerfile: barbaz.Dockerfile
